export type GeolocationMode='allow'|'ask'|'block';
export interface ProfileDraft{name:string;description:string;browserVersion:string;groupId:string;proxyId:string;userAgent:string;language:string;timezone:string;windowWidth:string;windowHeight:string;screenWidth:string;screenHeight:string;webrtcEnabled:boolean;geolocationMode:GeolocationMode;startupUrlsText:string;}
export interface ProfileValidationOptions{originalBrowserVersion?:string|undefined;browserVersionLocked:boolean;}
export interface ProfileTemplateConfigLike{browserVersion:string;groupId?:string|null;proxyId?:string|null;userAgent?:string|null;language?:string;timezone?:string;windowWidth?:number;windowHeight?:number;screenWidth?:number;screenHeight?:number;webrtcEnabled?:boolean;geolocationMode?:GeolocationMode;startupUrls?:string[];description?:string|null;}
export function isBrowserVersionLocked(runtimeState:string):boolean{return runtimeState!=='stopped';}
export function parseStartupUrls(text:string):string[]{const lines=text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);for(const value of lines){let url:URL;try{url=new URL(value);}catch{throw new Error(`Invalid URL: ${value}`);}if(url.protocol!=='http:'&&url.protocol!=='https:')throw new Error(`Unsupported URL protocol: ${value}`);}return lines;}
function positiveInteger(value:string):boolean{const n=Number(value);return Number.isInteger(n)&&n>0;}
export function validateProfileDraft(draft:ProfileDraft,options:ProfileValidationOptions):string[]{const errors:string[]=[];if(!draft.name.trim())errors.push('name');if(!draft.browserVersion.trim())errors.push('browserVersion');if(options.browserVersionLocked&&options.originalBrowserVersion!==undefined&&draft.browserVersion!==options.originalBrowserVersion)errors.push('browserVersion');for(const key of ['windowWidth','windowHeight','screenWidth','screenHeight'] as const)if(!positiveInteger(draft[key]))errors.push(key);try{parseStartupUrls(draft.startupUrlsText);}catch{errors.push('startupUrls');}return[...new Set(errors)];}
export function errorsForProfileStep(draft:ProfileDraft,step:number,options:ProfileValidationOptions):string[]{const all=validateProfileDraft(draft,options);const keys:readonly string[][]=[['name','browserVersion'],[],['windowWidth','windowHeight','screenWidth','screenHeight'],['startupUrls'],all];const allowed=keys[step]??[];return all.filter(error=>allowed.includes(error));}
export function buildProfileInput(draft:ProfileDraft){return{name:draft.name.trim(),description:draft.description.trim()||null,browserVersion:draft.browserVersion.trim(),groupId:draft.groupId||null,proxyId:draft.proxyId||null,userAgent:draft.userAgent.trim()||null,language:draft.language.trim(),timezone:draft.timezone.trim(),windowWidth:Number(draft.windowWidth),windowHeight:Number(draft.windowHeight),screenWidth:Number(draft.screenWidth),screenHeight:Number(draft.screenHeight),webrtcEnabled:draft.webrtcEnabled,geolocationMode:draft.geolocationMode,startupUrls:parseStartupUrls(draft.startupUrlsText)};}
export function applyTemplateToDraft(draft:ProfileDraft,config:ProfileTemplateConfigLike):ProfileDraft{return{...draft,description:config.description??'',browserVersion:config.browserVersion,groupId:config.groupId??'',proxyId:config.proxyId??'',userAgent:config.userAgent??'',language:config.language??draft.language,timezone:config.timezone??draft.timezone,windowWidth:String(config.windowWidth??draft.windowWidth),windowHeight:String(config.windowHeight??draft.windowHeight),screenWidth:String(config.screenWidth??draft.screenWidth),screenHeight:String(config.screenHeight??draft.screenHeight),webrtcEnabled:config.webrtcEnabled??draft.webrtcEnabled,geolocationMode:config.geolocationMode??draft.geolocationMode,startupUrlsText:(config.startupUrls??[]).join('\n')};}
