import { useEffect,useMemo,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import type { DesktopProfileListItem,UpdateProfileInput } from '@icrlogin/shared';
import { icrClient } from '../../api/icr-client.js';
import { buildProfileInput,errorsForProfileStep,isBrowserVersionLocked,validateProfileDraft,type ProfileDraft } from './profile-wizard-model.js';

const STEPS=['General','Proxy','Browser Environment','Startup URLs','Review'] as const;
function emptyDraft(browserVersion=''):ProfileDraft{return{name:'',description:'',browserVersion,groupId:'',proxyId:'',userAgent:'',language:'en-US',timezone:'UTC',windowWidth:'1280',windowHeight:'800',screenWidth:'1920',screenHeight:'1080',webrtcEnabled:true,geolocationMode:'ask',startupUrlsText:''};}
function fromProfile(profile:DesktopProfileListItem):ProfileDraft{return{name:profile.name,description:profile.description??'',browserVersion:profile.browserVersion,groupId:profile.groupId??'',proxyId:profile.proxyId??'',userAgent:profile.userAgent??'',language:profile.language,timezone:profile.timezone,windowWidth:String(profile.windowWidth),windowHeight:String(profile.windowHeight),screenWidth:String(profile.screenWidth),screenHeight:String(profile.screenHeight),webrtcEnabled:profile.webrtcEnabled,geolocationMode:profile.geolocationMode,startupUrlsText:profile.startupUrls.join('\n')};}

export interface ProfileWizardProps{open:boolean;profile:DesktopProfileListItem|null;onClose():void;}
export function ProfileWizard({open,profile,onClose}:ProfileWizardProps){
  const queryClient=useQueryClient();const[step,setStep]=useState(0);const[draft,setDraft]=useState<ProfileDraft>(()=>emptyDraft());const[errors,setErrors]=useState<string[]>([]);const[message,setMessage]=useState<string|null>(null);
  const groups=useQuery({queryKey:['groups'],queryFn:icrClient.groups.list,enabled:open});const proxies=useQuery({queryKey:['proxies'],queryFn:icrClient.proxies.list,enabled:open});const available=useQuery({queryKey:['browsers','available'],queryFn:icrClient.browsers.available,enabled:open,retry:0});const installed=useQuery({queryKey:['browsers','installed'],queryFn:icrClient.browsers.installed,enabled:open});
  const browserOptions=useMemo(()=>{const map=new Map<string,{version:string;stable:boolean}>();for(const item of installed.data??[])map.set(item.version,{version:item.version,stable:false});for(const item of available.data??[])map.set(item.version,{version:item.version,stable:item.isStable});if(profile&&!map.has(profile.browserVersion))map.set(profile.browserVersion,{version:profile.browserVersion,stable:false});return[...map.values()].sort((a,b)=>b.version.localeCompare(a.version,undefined,{numeric:true}));},[available.data,installed.data,profile]);
  const defaultVersion=browserOptions.find(item=>item.stable)?.version??browserOptions[0]?.version??'';
  const browserVersionLocked=profile?isBrowserVersionLocked(profile.runtimeState):false;
  useEffect(()=>{if(!open)return;setDraft(profile?fromProfile(profile):emptyDraft(defaultVersion));setStep(0);setErrors([]);setMessage(null);},[open,profile?.id,defaultVersion]);
  const save=useMutation({mutationFn:async()=>{const currentErrors=validateProfileDraft(draft,{originalBrowserVersion:profile?.browserVersion,browserVersionLocked});if(currentErrors.length){setErrors(currentErrors);throw new Error('Check the highlighted fields.');}const input=buildProfileInput(draft);if(!profile)return icrClient.profiles.create(input);if(browserVersionLocked){const{browserVersion:_locked,...safe}=input;return icrClient.profiles.update(profile.id,safe as UpdateProfileInput);}return icrClient.profiles.update(profile.id,input);},onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:['profiles']});onClose();},onError:error=>setMessage(error instanceof Error?error.message:'Unable to save profile')});
  if(!open)return null;const patch=<K extends keyof ProfileDraft>(key:K,value:ProfileDraft[K])=>setDraft(current=>({...current,[key]:value}));const invalid=(key:string)=>errors.includes(key)?' field-invalid':'';
  const next=()=>{const currentErrors=errorsForProfileStep(draft,step,{originalBrowserVersion:profile?.browserVersion,browserVersionLocked});if(currentErrors.length){setErrors(currentErrors);return;}setErrors([]);setStep(value=>Math.min(STEPS.length-1,value+1));};
  return <div className="modal-backdrop" role="presentation"><section className="wizard-modal" role="dialog" aria-modal="true" aria-label={profile?'Edit profile':'Create profile'}><header className="wizard-header"><div><p className="eyebrow">{profile?'EDIT PROFILE':'NEW PROFILE'}</p><h2>{profile?profile.name:'Create profile'}</h2></div><button className="modal-close" onClick={onClose} aria-label="Close">×</button></header><div className="wizard-steps">{STEPS.map((label,index)=><div key={label} className={index===step?'wizard-step active':index<step?'wizard-step complete':'wizard-step'}><span>{index+1}</span>{label}</div>)}</div><div className="wizard-body">
    {step===0&&<div className="form-grid"><label className="field wide"><span>Name *</span><input className={invalid('name')} value={draft.name} onChange={e=>patch('name',e.target.value)} autoFocus/></label><label className="field"><span>Group</span><select value={draft.groupId} onChange={e=>patch('groupId',e.target.value)}><option value="">Ungrouped</option>{(groups.data??[]).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="field"><span>Chromium version *</span><select className={invalid('browserVersion')} value={draft.browserVersion} disabled={browserVersionLocked} onChange={e=>patch('browserVersion',e.target.value)}><option value="">Select version</option>{browserOptions.map(item=><option key={item.version} value={item.version}>{item.version}{item.stable?' — Stable':''}</option>)}</select>{browserVersionLocked&&<small>Stop this profile to change browser version.</small>}</label><label className="field wide"><span>Description</span><textarea rows={3} value={draft.description} onChange={e=>patch('description',e.target.value)}/></label></div>}
    {step===1&&<div className="form-grid"><label className="field wide"><span>Proxy</span><select value={draft.proxyId} onChange={e=>patch('proxyId',e.target.value)}><option value="">No proxy / Direct</option>{(proxies.data??[]).map(p=><option key={p.id} value={p.id}>{p.name} — {p.type.toUpperCase()} {p.host}:{p.port}</option>)}</select><small>Credentials stay encrypted in the main process and are never shown here.</small></label></div>}
    {step===2&&<div className="form-grid"><label className="field wide"><span>User-Agent</span><input value={draft.userAgent} placeholder="Default Chromium UA" onChange={e=>patch('userAgent',e.target.value)}/></label><label className="field"><span>Language</span><input value={draft.language} onChange={e=>patch('language',e.target.value)}/></label><label className="field"><span>Timezone</span><input value={draft.timezone} onChange={e=>patch('timezone',e.target.value)}/></label><label className="field"><span>Window size</span><div className="inline-fields"><input className={invalid('windowWidth')} value={draft.windowWidth} onChange={e=>patch('windowWidth',e.target.value)}/><b>×</b><input className={invalid('windowHeight')} value={draft.windowHeight} onChange={e=>patch('windowHeight',e.target.value)}/></div></label><label className="field"><span>Screen resolution</span><div className="inline-fields"><input className={invalid('screenWidth')} value={draft.screenWidth} onChange={e=>patch('screenWidth',e.target.value)}/><b>×</b><input className={invalid('screenHeight')} value={draft.screenHeight} onChange={e=>patch('screenHeight',e.target.value)}/></div></label><label className="field"><span>WebRTC</span><select value={draft.webrtcEnabled?'on':'off'} onChange={e=>patch('webrtcEnabled',e.target.value==='on')}><option value="on">On</option><option value="off">Off</option></select></label><label className="field"><span>Geolocation</span><select value={draft.geolocationMode} onChange={e=>patch('geolocationMode',e.target.value as ProfileDraft['geolocationMode'])}><option value="allow">Allow</option><option value="ask">Ask</option><option value="block">Block</option></select></label></div>}
    {step===3&&<label className="field wide"><span>Startup URLs — one per line</span><textarea className={invalid('startupUrls')} rows={10} placeholder={'https://example.com\nhttp://localhost:3000'} value={draft.startupUrlsText} onChange={e=>patch('startupUrlsText',e.target.value)}/><small>Only HTTP and HTTPS URLs are accepted.</small></label>}
    {step===4&&<div className="review-grid"><div><span>Name</span><strong>{draft.name||'—'}</strong></div><div><span>Browser</span><strong>{draft.browserVersion||'—'}</strong></div><div><span>Group</span><strong>{(groups.data??[]).find(g=>g.id===draft.groupId)?.name??'Ungrouped'}</strong></div><div><span>Proxy</span><strong>{(proxies.data??[]).find(p=>p.id===draft.proxyId)?.name??'Direct'}</strong></div><div><span>Environment</span><strong>{draft.language} · {draft.timezone}</strong></div><div><span>Startup tabs</span><strong>{draft.startupUrlsText.split(/\r?\n/).filter(line=>line.trim()).length}</strong></div></div>}
    {message&&<div className="form-error">{message}</div>}
  </div><footer className="wizard-footer"><button className="btn" onClick={onClose}>Cancel</button><div className="wizard-footer-right">{step>0&&<button className="btn" onClick={()=>setStep(value=>value-1)}>Back</button>}{step<STEPS.length-1?<button className="btn primary" onClick={next}>Next</button>:<button className="btn primary" disabled={save.isPending||!draft.browserVersion} onClick={()=>save.mutate()}>{save.isPending?'Saving…':profile?'Save changes':'Create profile'}</button>}</div></footer></section></div>;
}
